### ISSUE TITLE
Clipboard paste/copy/cut bug.

### ISSUE THREAD

**Issue by gary17** [giuspen/cherrytree#114]
Copying, cutting and pasting multiple times successively, in an unknown order, into a Rich Text node (possibly involving URLs as the pasted content) causes the clipboard subsystem to stop responding (no longer copies, cuts or pastes). Upon application shutdown, the following error is logged to `cherrytree.exe.log`:

    Traceback (most recent call last):
      File "clipboard.pyc", line 98, in copy
      File "clipboard.pyc", line 162, in selection_to_clipboard
      File "exports.pyc", line 651, in selection_export_to_html
      File "exports.pyc", line 832, in html_get_from_rich_text_selection
      File "exports.pyc", line 853, in html_process_slot
      File "exports.pyc", line 895, in html_text_serialize
      File "exports.pyc", line 53, in rgb_48_to_48_no_white
    ValueError: invalid literal for int() with base 16: ''

Or:

    Traceback (most recent call last):
      File "clipboard.pyc", line 111, in cut
      File "clipboard.pyc", line 162, in selection_to_clipboard
      File "exports.pyc", line 651, in selection_export_to_html
      File "exports.pyc", line 832, in html_get_from_rich_text_selection
      File "exports.pyc", line 853, in html_process_slot
      File "exports.pyc", line 895, in html_text_serialize
      File "exports.pyc", line 53, in rgb_48_to_48_no_white
    ValueError: invalid literal for int() with base 16: ''

Environment: CherryTree 0.36.5, Windows 10 x64.

**Comment by giuspen** [comment]
This bug should be already fixed in 0.36.6, please verify

**Comment by gary17** [comment]
Confirmed as fixed, thanks!
