### ISSUE TITLE
sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by AdamF800** [giuspen/cherrytree#120]
I've been using Cherrytree on my Windows Vista computer for a few months now and have really enjoyed it until recently as it will no longer run.
Every time I try, I get an error window that sends me to the log.
In the log I find:

Traceback (most recent call last):
  File "cherrytree", line 70, in <module>
  File "cherrytree", line 48, in f_main
  File "main.pyc", line 219, in main
  File "main.pyc", line 64, in __init__
  File "main.pyc", line 69, in window_open_new
  File "core.pyc", line 203, in __init__
  File "core.pyc", line 1346, in file_startup_load
  File "core.pyc", line 1935, in file_load
  File "ctdb.pyc", line 597, in read_db_full
  File "ctdb.pyc", line 575, in read_db_node_n_children
  File "ctdb.pyc", line 537, in get_node_row_partial_from_id
sqlite3.DatabaseError: database disk image is malformed

I've been trying on my own to fix it, but I'm pretty illiterate when it comes to coding and none of my searches for a solution has given me any results.

**Comment by giuspen** [comment]
Hello Adam, I'm sorry to hear that your database got corrupted, you should have 3 different time based backups for it though, please check the same folder of the db for files with the same name but additional trailing one, two and three tildes. Just remove the tildes and open. Let me know.

**Comment by AdamF800** [comment]
That worked. I can open my file again and just about everything is there. That worked so well and was so simple that it makes me feel like an idiot.
Thanks for the help!
