### ISSUE TITLE
object has no attribute 'place_cursor'

### ISSUE THREAD

**Issue by krisko** [giuspen/cherrytree#122]
Hi, I'm recently getting this err when trying to start cherry tree... any clue what this could be?

<pre>
Traceback (most recent call last):
  File "/home/krisko/pkgs2/share/cherrytree/modules/core.py", line 2954, in on_node_changed
    self.set_sourcebuffer_with_style_scheme()
  File "/home/krisko/pkgs2/share/cherrytree/modules/core.py", line 2573, in set_sourcebuffer_with_style_scheme
    self.sourcebuffers[style_scheme].set_style_scheme(self.sourcestyleschememanager.get_scheme(style_scheme))
TypeError: GtkSourceView.Buffer.set_style_scheme() argument 1 must be gtksourceview2.StyleScheme, not None
Traceback (most recent call last):
  File "/home/krisko/pkgs2/bin/cherrytree", line 72, in <module> 
    f_main(args)
  File "/home/krisko/pkgs2/bin/cherrytree", line 50, in f_main
    main.main(args)
  File "/home/krisko/pkgs2/share/cherrytree/modules/main.py", line 219, in main
    CherryTreeHandler(args, lang_str)
  File "/home/krisko/pkgs2/share/cherrytree/modules/main.py", line 64, in __init__ 
    self.window_open_new(filepath_fix(args.filepath), args.node, True, True if args.filepath else False)
  File "/home/krisko/pkgs2/share/cherrytree/modules/main.py", line 69, in window_open_new
    window = core.CherryTree(self.lang_str, filepath, node_name, self, is_startup, is_arg, False)
  File "/home/krisko/pkgs2/share/cherrytree/modules/core.py", line 228, in __init__ 
    self.file_startup_load(open_with_file, node_name)
  File "/home/krisko/pkgs2/share/cherrytree/modules/core.py", line 1442, in file_startup_load
    config.set_tree_path_and_cursor_pos(self)
  File "/home/krisko/pkgs2/share/cherrytree/modules/config.py", line 555, in set_tree_path_and_cursor_pos
    inst.curr_buffer.place_cursor(inst.curr_buffer.get_iter_at_offset(inst.cursor_position))
AttributeError: 'NoneType' object has no attribute 'place_cursor'
</pre>

As you can see, I'm running custom installation, with cherrytree and python (and all libraries) in non-standart path. But yesterday, it worked and today it doesn't and I haven't been doing any critical changes in the system...

**Comment by krisko** [comment]
I've removed my current ctb database, started cherrytree (successfully), then copied the database back, restarted cherrytree and now it's working.

**Comment by krisko** [comment]
OK so the solution is pretty simple:
<pre>
cp -ar ~pkgs2/usr/share/gtksourceview-2.0/* ~/.local/share/gtksourceview-2.0/
</pre>

I had to copy schemes to my local folder, because they weren't found in the custom path.
So no problem at all.
Sorry to SPAM you. I have to run cherrytree like this, because I don't have python-gtksourceview available in my repos.

**Comment by giuspen** [comment]
Ok no worries thanks for the explanation
