### ISSUE TITLE
Linux: 0.39 crashes on 0.99 file

### ISSUE THREAD

**Issue by jochen-01** [giuspen/cherrytree#1250]
Ubuntu 18.04 / 20.04
When trying to open a file written with cherrytree 0.99 in cherrytree 0.39 part of the file is loaded. Cannot find out which part of the file causes the problem. It happens in file format unprotected XML as well as unprotected sqlite.
When closing the program window cherrytree crashes.

```** (cherrytree:16354): WARNING **: 21:09:36.437: Invalid borders specified
for theme pixmap:
        /usr/share/themes/Breeze/gtk-2.0/../assets/line-h.png, borders don't fit within the image
Traceback (most recent call last):
  File "/usr/share/cherrytree/modules/core.py", line 1782, in file_open
    self.filepath_open(filepath)
  File "/usr/share/cherrytree/modules/core.py", line 1832, in filepath_open
    self.file_load(filepath)
  File "/usr/share/cherrytree/modules/core.py", line 2036, in file_load
    if self.xml_handler.dom_to_treestore(cherrytree_string, discard_ids=None):
  File "/usr/share/cherrytree/modules/machines.py", line 114, in dom_to_treestore
    self.append_tree_node(dom_iter, tree_father, discard_ids, node_sequence, next_id_box)
  File "/usr/share/cherrytree/modules/machines.py", line 190, in append_tree_node
    self.append_tree_node(child_dom_iter, tree_iter, discard_ids, child_sequence, next_id_box)
  File "/usr/share/cherrytree/modules/machines.py", line 190, in append_tree_node
    self.append_tree_node(child_dom_iter, tree_iter, discard_ids, child_sequence, next_id_box)
  File "/usr/share/cherrytree/modules/machines.py", line 156, in append_tree_node
    elif child_dom_iter.nodeName == "encoded_png":
self.image_deserialize(curr_buffer, child_dom_iter, 2)
  File "/usr/share/cherrytree/modules/machines.py", line 253, in image_deserialize
    pixbuf.time = float(dom_node.attributes["time"].value) if dom_node.hasAttribute("time") else 0
ValueError: invalid literal for float(): 1560255882,000000

Gtk:ERROR:/build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gtk/gtktextbtree.c:4746:gtk_text_line_destroy:
assertion failed: (view != NULL)
Abgebrochen (core dumped)
```

**Comment by jochen-01** [comment]
Ubuntu 18.04 / 20.04
When trying to open a file written with cherrytree 0.99 in cherrytree 0.39 part of the file is loaded. Cannot find out which part of the file causes the problem. It happens in file format unprotected XML as well as unprotected sqlite.
When closing the program window cherrytree crashes.

```** (cherrytree:16354): WARNING **: 21:09:36.437: Invalid borders specified
for theme pixmap:
        /usr/share/themes/Breeze/gtk-2.0/../assets/line-h.png, borders don't fit within the image
Traceback (most recent call last):
  File "/usr/share/cherrytree/modules/core.py", line 1782, in file_open
    self.filepath_open(filepath)
  File "/usr/share/cherrytree/modules/core.py", line 1832, in filepath_open
    self.file_load(filepath)
  File "/usr/share/cherrytree/modules/core.py", line 2036, in file_load
    if self.xml_handler.dom_to_treestore(cherrytree_string, discard_ids=None):
  File "/usr/share/cherrytree/modules/machines.py", line 114, in dom_to_treestore
    self.append_tree_node(dom_iter, tree_father, discard_ids, node_sequence, next_id_box)
  File "/usr/share/cherrytree/modules/machines.py", line 190, in append_tree_node
    self.append_tree_node(child_dom_iter, tree_iter, discard_ids, child_sequence, next_id_box)
  File "/usr/share/cherrytree/modules/machines.py", line 190, in append_tree_node
    self.append_tree_node(child_dom_iter, tree_iter, discard_ids, child_sequence, next_id_box)
  File "/usr/share/cherrytree/modules/machines.py", line 156, in append_tree_node
    elif child_dom_iter.nodeName == "encoded_png":
self.image_deserialize(curr_buffer, child_dom_iter, 2)
  File "/usr/share/cherrytree/modules/machines.py", line 253, in image_deserialize
    pixbuf.time = float(dom_node.attributes["time"].value) if dom_node.hasAttribute("time") else 0
ValueError: invalid literal for float(): 1560255882,000000

Gtk:ERROR:/build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gtk/gtktextbtree.c:4746:gtk_text_line_destroy:
assertion failed: (view != NULL)
Abgebrochen (core dumped)
```

**Comment by giuspen** [comment]
I will do some testing about this shortly thanks, a document edited with a 0.99.x is still meant to be edited with 0.39.x

**Comment by giuspen** [comment]
please try again to save in 0.99.16 and then open with 0.39.4

**Comment by jochen-01** [comment]
Thank you, it works!
