### ISSUE TITLE
file is encrypted or is not a database

### ISSUE THREAD

**Issue by azharbajened** [giuspen/cherrytree#1256]
hii ..
do you have any idea for this issue ?

Traceback (most recent call last):
  File "core.pyc", line 1780, in file_open
  File "core.pyc", line 1830, in filepath_open
  File "core.pyc", line 2038, in file_load
  File "ctdb.pyc", line 637, in read_db_full
sqlite3.DatabaseError: file is encrypted or is not a database

my note cannot opened because of that..
i need your help..

**Comment by giuspen** [comment]
Can you try with 0.99.15?

**Comment by azharbajened** [comment]
> 
> 
> Can you try with 0.99.15?

Yes sir, im already try for that version. The error pop up give me the notification like this : 
error while adding ts_creation and ts_lastsave to note table::sqlite3 'ALTER TABLE node ADD COLUMN ts_cteation INTEGER':file is not a database

**Comment by giuspen** [comment]
If you haven't disabled the backups you should have three files with the same name of your cherrytree document but trailing tildes (~) can you open any of those after removing the tildes?

**Comment by azharbajened** [comment]
hi sir, 
yes im already try.. but still cannot opened (geting same error) and i get the back up like this :
file.ctb = 51.074 KB
file.ctb~ = 256 KB
file.ctb~~ = 736 KB
file.ctb~~~ = 96 KB

thats different size..

**Comment by giuspen** [comment]
If you try and open the document with https://sqlitebrowser.org/ is it showing any table? there should be 6 tables
