### ISSUE TITLE
loose note content

### ISSUE THREAD

**Issue by user216** [giuspen/cherrytree#1482]
when I open note - dont see any content  on it :(

```
5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

~ $ snap info cherrytree
name:      cherrytree
summary:   Hierarchical note taking application
publisher: Heather Ellsworth (hellsworth)
store-url: https://snapcraft.io/cherrytree
contact:   heather.ellsworth@canonical.com
license:   unset
description: |
  A hierarchical note taking application, featuring rich text and syntax highlighting, storing data
  in a single XML or SQLite file. The project home page is giuspen.com/cherrytree.
commands:
  - cherrytree
snap-id:      ne8DjJO8ts6inYLWUlDs3jLlrITuHrJV
tracking:     latest/stable
refresh-date: today at 22:12 EET
channels:
  latest/stable:    0.39.4  2020-07-09 (28) 72MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      0.99.24 2020-12-17 (36) 71MB -
installed:          0.39.4             (28) 72MB -
$ cherrytree
ln: failed to create symbolic link '/home/andrii/snap/cherrytree/28/.config/gtk-2.0/gtkfilechooser.ini': File exists
sel node id=1163, seq=2
Traceback (most recent call last):
  File "/snap/cherrytree/28/share/cherrytree/modules/core.py", line 3171, in on_node_changed
    if self.enable_spell_check: self.spell_check_set_on()
  File "/snap/cherrytree/28/share/cherrytree/modules/core.py", line 4844, in spell_check_set_on
    self.spellchecker = pgsc_spellcheck.SpellChecker(self.sourceview, self, self.syntax_highlighting == cons.RICH_TEXT_ID, self.spell_check_lang)
  File "/snap/cherrytree/28/share/cherrytree/modules/pgsc_spellcheck.py", line 202, in __init__
    raise NoDictionariesFound()
pgsc_spellcheck.NoDictionariesFound

**Comment by giuspen** [comment]
Upgrade to 0.99.29
