### ISSUE TITLE
Enabling Spellcheck without dictionaries locks the tree

### ISSUE THREAD

**Issue by Dimonade** [giuspen/cherrytree#1718]
Good day, 

I have encountered the following behaviour on Cherry Tree while playing with the preferences:

**Version, Operative system**
Ubuntu 20.04.2 LTS;

**Describe the bug**
Changing Edit -> Preferences -> Rich Text -> Spell Check to enabled (ticked) while no spellcheck language dictionary is available locks the whole tree.
Selecting (highlighting) different nodes works, but nothing on the screen changes.
Export, save, load are not working, raising Write to disk error occasionally.  

**To Reproduce**
1. Go to Edit -> Preferences -> Rich Text -> Spell Check -> Enable.
2. Must have no dictionaries.
3. Save and close preferences.
4. Try to navigate in the nodes. While nodes are being highlighted, the text panel stays on the latest node.
5. Restarting Cherry Tree loads the last node with the exact behaviour.
6. Exporting or Save as... the file occasionally raises Write to disk error.

**Findings**
Launching Cherry Tree through the terminal reveals the following traceback which leads to the spellchecker configuration.
```
[user]@[machine]:~$ cherrytree 
ln: failed to create symbolic link '/home/[user]/snap/cherrytree/40/.config/gtk-2.0/gtkfilechooser.ini': File exists
Gtk-Message: 23:44:45.650: Failed to load module "gail"
Gtk-Message: 23:44:45.650: Failed to load module "atk-bridge"
Gtk-Message: 23:44:45.656: Failed to load module "canberra-gtk-module"
sel node id=20, seq=3
Traceback (most recent call last):
  File "/snap/cherrytree/40/usr/share/cherrytree/modules/core.py", line 3171, in on_node_changed
    if self.enable_spell_check: self.spell_check_set_on()
  File "/snap/cherrytree/40/usr/share/cherrytree/modules/core.py", line 4844, in spell_check_set_on
    self.spellchecker = pgsc_spellcheck.SpellChecker(self.sourceview, self, self.syntax_highlighting == cons.RICH_TEXT_ID, self.spell_check_lang)
  File "/snap/cherrytree/40/usr/share/cherrytree/modules/pgsc_spellcheck.py", line 202, in __init__
    raise NoDictionariesFound()
pgsc_spellcheck.NoDictionariesFound
```

While clicking on another node, the following traceback appended:
```
Traceback (most recent call last):
  File "/snap/cherrytree/40/usr/share/cherrytree/modules/core.py", line 3131, in on_node_changed
    self.spell_check_set_off()
  File "/snap/cherrytree/40/usr/share/cherrytree/modules/core.py", line 4854, in spell_check_set_off
    if self.spell_check_init: self.spellchecker.disable()
AttributeError: CherryTree instance has no attribute 'spellchecker'
```

This led me to either downloading the spellchecker dictionaries or to return the configuration file back to normal.
`gedit ~/snap/cherrytree/40/.config/cherrytree/config.cfg `

Finding the lines
```
spell_check_lang = 
enable_spell_check = True
```

Reverting them back to
```
spell_check_lang = 
enable_spell_check = false
```

Returns the behaviour back to normal.

**Expected behaviour**
If no dictionaries are available the spellcheck option is disabled.
Or perhaps if still enabled and then ticked, a popup will warn about lack of dictionaries and clear the tick.

**Misc**
libcanberra is installed on the system despite the warning:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcanberra-gtk-module is already the newest version (0.30-7ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Thank you very much,
Dimonade.

**Comment by giuspen** [comment]
Thanks I'll sort this out

**Comment by Dimonade** [comment]
Will do.
Thank you very much!
