### ISSUE TITLE
KeyError: -1

### ISSUE THREAD

**Issue by mlleparker** [giuspen/cherrytree#173]
Hi,

I run Debian in lastest version & I'm up to date. I have a little bug with 0.37.x but not with older versions.

$ cherrytree 
Traceback (most recent call last):
  File "/usr/bin/cherrytree", line 72, in <module>
    f_main(args)
  File "/usr/bin/cherrytree", line 50, in f_main
    main.main(args)
  File "/usr/share/cherrytree/modules/main.py", line 221, in main
    CherryTreeHandler(args, lang_str)
  File "/usr/share/cherrytree/modules/main.py", line 64, in __init__
    self.window_open_new(filepath_fix(args.filepath), args.node, True, True if args.filepath else False)
  File "/usr/share/cherrytree/modules/main.py", line 69, in window_open_new
    window = core.CherryTree(self.lang_str, filepath, node_name, self, is_startup, is_arg, False)
  File "/usr/share/cherrytree/modules/core.py", line 221, in __init__
    self.file_startup_load(open_with_file, node_name)
  File "/usr/share/cherrytree/modules/core.py", line 1449, in file_startup_load
    self.file_load(os.path.join(self.file_dir, self.file_name))
  File "/usr/share/cherrytree/modules/core.py", line 2045, in file_load
    self.ctdb_handler.read_db_full(self.db, discard_ids=False)
  File "/usr/share/cherrytree/modules/ctdb.py", line 622, in read_db_full
    node_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 607, in read_db_node_n_children
    child_sequence)
  File "/usr/share/cherrytree/modules/ctdb.py", line 576, in read_db_node_n_children
    cherry = self.dad.get_node_icon(node_level, syntax_highlighting, custom_icon_id)
  File "/usr/share/cherrytree/modules/core.py", line 277, in get_node_icon
    stock_id = cons.NODES_ICONS[-1]
KeyError: -1

If someone have an idea... :)
For the moment, I use the latest 0.36.x.

**Comment by giuspen** [comment]
Thanks for the report, I should have fixed this problem now. Can you test the git master version and confirm that the bug is fixed? If you need me to create a package for you let me know

**Comment by mlleparker** [comment]
Hello and thank's a lot :)
I've tested your master branch and the problem is solved for me. Here a screenshot to show you CherryTree starts correctly.

https://debian-facile.org/images/file-Rbb015fd460258ea1b059ff1cf2dabe8f

I use Cherrytree for a long time, so if you need help (like beta tests), let me know, I will be delighted to help. :)

**Comment by giuspen** [comment]
Great thanks :) After I'll port the app from GTK2 to GTK3 your help would be very useful to verify that everything is still working

**Comment by mlleparker** [comment]
With great pleasure. :)
