### ISSUE TITLE
The problem of imports from Tomboy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giuspen/cherrytree#21]
```
Messages:
Traceback (most recent call last):
  File "/usr/share/cherrytree/modules/core.py", line 830, in nodes_add_from_tomboy_folder
    cherrytree_string = tomboy.get_cherrytree_xml()
  File "/usr/share/cherrytree/modules/imports.py", line 937, in get_cherrytree_xml
    self.start_parsing()
  File "/usr/share/cherrytree/modules/imports.py", line 797, in start_parsing
    self.doc_parse(xml_string, element)
  File "/usr/share/cherrytree/modules/imports.py", line 810, in doc_parse
    child_dom_iter = dom_iter.firstChild
AttributeError: 'NoneType' object has no attribute 'firstChild'

Solution:

In /usr/share/cherrytree/modules/imports.py
After line 805, insert the following code:

if file_name == "manifest.xml": return

```

Original issue reported on code.google.com by `lominogagv@gmail.com` on 4 Jan 2015 at 2:45

**Comment by luiandresgonzalez** [comment]
I'm having this issue on Windows 10 while trying to import Tomboy Notes from a folder. 
Here's the cherrytree.exe.log

`Traceback (most recent call last):
  File "core.pyc", line 964, in nodes_add_from_tomboy_folder
  File "imports.pyc", line 1271, in get_cherrytree_xml
  File "imports.pyc", line 1131, in start_parsing
  File "imports.pyc", line 1144, in doc_parse
AttributeError: 'NoneType' object has no attribute 'firstChild'`

I cannot find those files while trying to solve it.

**Comment by giuspen** [comment]
I can help if you give me data that let me reproduce the issue (zipped folder you are trying to import)

**Comment by luiandresgonzalez** [comment]
Since I don't want the folder to be public, I sent you a link to the zipped folder through http://www.giuspen.com/feedback/.

Best regards.

**Comment by luiandresgonzalez** [comment]
​Problem solved.

Tomboy Notes has this local directory sync service which allows to select other folder for the files (in my case was important for Dropbox and dual boot integration). I was choosing _that_ folder and not the actual C:\Users\[USER]\AppData\Roaming\Tomboy\notes​ folder, where the actual files are stored.
