### ISSUE TITLE
CherryTree froze and could not be ended/killed.

### ISSUE THREAD

**Issue by firepainting** [giuspen/cherrytree#2187]
This is mainly for reporting what happened to my PC.

**Version, Operative system**
CherryTree Version 0.99.53
Linux Mint 21.1 Cinnamon

**Describe the bug**
CherryTree froze and could not be ended/killed.

**To Reproduce**
I could **NOT** reproduce the issue, but this is what happened:
• Exported 1 node (with subnodes) from “DATABASE 1”. (“DATABASE 1” is around 25 MB.)
• “Save and Vacuum” “DATABASE 1”.
• CherryTree started to Not Responding. “Force Quit” dialog box appeared, which I clicked but it would not.
• `xkill` on terminal then clicked on freezing CherryTree, then it closed the app, but in System Monitor `cherrytree` was still running. CPU went kinda high, temp was around 53 degrees C.
• These did NOT work: `killall cherrytree` `kill cherrytree` `pkill cherrytree`
• Mounted Cryptomator could not lock (and unmount).
• File Manager Nemo also started to not respond.

It was "solved" by a PC reboot. Note that Cryptomator was still mounted and CPU was running high upon the reboot.

Thankfully my CherryTree files seem fine after that.

Here's a crash report I got (I hope it helps):
```
===================================================================
 Info                                                              
===================================================================
           PID: 62084 (cherrytree)
           UID: 1000 (myname)
           GID: 1000 (myname)
        Signal: 6 (ABRT)
     Timestamp: Thu 2022-12-29 18:35:40 (3min 54s ago)
  Command Line: cherrytree --new_window
    Executable: /usr/bin/cherrytree
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (myname)
       Boot ID: 0f1356bcd271495fb51c5931de6fe22d
    Machine ID: b0d275fb46fa48c6820be57edaa22cf5
      Hostname: mypcname
       Storage: /var/lib/systemd/coredump/core.cherrytree.1000.0f1356bcd271495fb51c5931de6fe22d.62084.1672310140000000.zst (present)
     Disk Size: 1.3M
       Message: Process 62084 (cherrytree) of user 1000 dumped core.
                
                Found module linux-vdso.so.1 with build-id: 21a2739157f98ff49d8920f47723a6a3ddb1f4d1
                Found module libgvfscommon.so with build-id: e7fa580fb91bb21aac9fc69229e0961dc743f2b1
                Found module libgvfsdbus.so with build-id: 28abe694dac468552cc1d23d6f643e7989de85e8
                Found module libxkbfile.so.1 with build-id: b585f533dd10bd8c043f887705d4e45828baf206
                Found module libxklavier.so.16 with build-id: a581072418d786fb4a1d160ee7143bbd977025e7
                Found module libgnomekbd.so.8 with build-id: 636c4ae86d1bff2aa2cb92b39b42e41ff714ec7c
                Found module libgnomekbdui.so.8 with build-id: e01ea8bdf45e3995a2449f1cb4bd8e6bd886efa5
                Found module libxapp.so.1 with build-id: c2604faecc8b0da20c901263b5c716224cd5818e
                Found module libxapp-gtk3-module.so with build-id: a879184917c79399c48158e5c6f139cd89499ab4
                Found module libmd.so.0 with build-id: cd2d2f71b3967ebde30e2aa43b8eb63339020c06
                Found module libgpg-error.so.0 with build-id: 3fbec71c67bee60d8aef00697ee187079b0fb307
                Found module libresolv.so.2 with build-id: 7fd7253c61aa6fce2b7e13851c15afa14a5ab160
                Found module libkeyutils.so.1 with build-id: ff27227afa5eeddccab180dd29bd7fcff94aea7c
                Found module libbsd.so.0 with build-id: 9a6c72469251e2feb63e175ef5cb944ce6e00df3
                Found module libgcrypt.so.20 with build-id: 60a5e524de0ed8323edf33e9eb9127a9eee02359
                Found module libcap.so.2 with build-id: 9e11e3bca4b0a25d047cb36e933e1d727663cf8e
                Found module liblz4.so.1 with build-id: a85971851cd059f1af80d553c8e7170d42ec59a1
                Found module libtasn1.so.6 with build-id: 2fde6ecb43c586fe4077118f771077aa1298e7ea
                Found module libp11-kit.so.0 with build-id: a0ffe1d002de5812dc718186172efb78604ddf2c
                Found module libbrotlicommon.so.1 with build-id: 43a72967cf84155914c8b3e915926733d1e57c11
                Found module libsasl2.so.2 with build-id: 562c038e4a5a2196c9c085cd1f9276e3641399a6
                Found module libkrb5support.so.0 with build-id: f9dcbdef069078853fc0d3d7fbfc9bbb923cfe3c
                Found module libcom_err.so.2 with build-id: ce0901f10854b3c9276066b98d9a72303206e0d5
                Found module libk5crypto.so.3 with build-id: 1b22be74b69ba5fcd325664ba47bf9e87bf7d530
                Found module libkrb5.so.3 with build-id: c840d413c769ab9bcbcd12740eca61e5a969cce3
                Found module libgmp.so.10 with build-id: f110719303ddbea25a5e89ff730fec520eed67b0
                Found module libnettle.so.8 with build-id: 3d9c6bf106ef53d625b7b1c8bb1300e84598a74a
                Found module libhogweed.so.6 with build-id: 3cc4a3474de72db89e9dcc93bfb95fe377f48c37
                Found module libunistring.so.2 with build-id: ca5149da8d5a298b8f286ffca3d6e2402ec0fe01
                Found module libXdmcp.so.6 with build-id: 6b60f99504aa1d3999ea02a14366d1a39d6c5dcf
                Found module libXau.so.6 with build-id: 7089b383cacbfc1760634a3be19a923e51fe3315
                Found module libdatrie.so.1 with build-id: 128b6874a47f2b783d9e9060d3caaee4110bfd3d
                Found module libblkid.so.1 with build-id: cdf95a964e3302bb356fefc4b801fae8c4340b31
                Found module libuuid.so.1 with build-id: 64c0d0cb22fa2bdeca075a0c0418ba5ff314b220
                Found module libexpat.so.1 with build-id: d212d1f61d04a1e60fccad1a8c118428cfd9be42
                Found module libgraphite2.so.3 with build-id: 5ffbc76fc948f6b88d766a7210c2e6a329a6c278
                Found module libatspi.so.0 with build-id: 2843c68233d5ba81da3d6bc31422e49472873dba
                Found module libdbus-1.so.3 with build-id: 63e8b99215502138cb63afd6d65851a5e837ed49
                Found module libjpeg.so.8 with build-id: c54abff9294357e28532a76a049a4cb2542fc15b
                Found module libpcre.so.3 with build-id: 3982f316c887e3ad9598015fa5bae8557320476a
                Found module libffi.so.8 with build-id: 59c2a6b204f74f358ca7711d2dfd349d88711f6a
                Found module ld-linux-x86-64.so.2 with build-id: 61ef896a699bb1c2e4e231642b2e1688b2f1a61e
                Found module libsystemd.so.0 with build-id: 61fb1ea64197576f79977fb27e1be39a088e7f3e
                Found module libpcre2-8.so.0 with build-id: 184a841c55fb7fe5e3873fcda8368c71016cd54c
                Found module libgnutls.so.30 with build-id: b9fa7b6d0c47adb8a3f03b2452c3df3eb2c93715
                Found module libbrotlidec.so.1 with build-id: 4b1f390dd6e24d49684db8b2443d082379e8e977
                Found module libzstd.so.1 with build-id: 5d9d0d946a3154a748e87e17af9d14764519237b
                Found module liblber-2.5.so.0 with build-id: 825836c4cd2ce3c7b6369bfe2812511529112f6a
                Found module libldap-2.5.so.0 with build-id: 111d8323d815e64f2f486e4a3ce0085c92f1d2b8
                Found module libgssapi_krb5.so.2 with build-id: cfb0a0611861784ae85210cca6e5cc729e554c23
                Found module libcrypto.so.3 with build-id: 0c369eae63403647fb36564ae61733900d651702
                Found module libssl.so.3 with build-id: e2cc2e6cff81fe9dc26f9d03e9865a0d1964ed95
                Found module libpsl.so.5 with build-id: 2b1afc1a3bc8bdb016e432c50db058632e7895b9
                Found module libssh.so.4 with build-id: f6a2eb7d2d6c5a8e3b7a9b2dcb3fa9ab394cf2b5
                Found module librtmp.so.1 with build-id: 9517ef375cd71ea3da824b4118f1599735093d66
                Found module libidn2.so.0 with build-id: 45b73e0e1c46a76be22f572ee98c60af5768bf8f
                Found module libnghttp2.so.14 with build-id: 90a67111383c58bfff9fac96da818cc62e5b68c9
                Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265
                Found module libicudata.so.70 with build-id: b1c2496dd0543023c7a19c961bb7f3abc818f465
                Found module libicuuc.so.70 with build-id: bef3ff1d70aadd68aab07d858a759360c8b919ae
                Found module libenchant-2.so.2 with build-id: 6567af9845ef81015bb3eb15df79c7322ad55a08
                Found module libgtksourceview-3.0.so.1 with build-id: 8a749a5ab4e946c3520e2186661046fbef342175
                Found module libXrender.so.1 with build-id: 7ccbfa4c24e93c42fa50dd2e42fa277630f9650c
                Found module libxcb-render.so.0 with build-id: cb521131fd3b0f2ee6056cbc2014b3b8ef0d5c0e
                Found module libxcb.so.1 with build-id: 1bef862a339557aa16c34c7a4b27f8f3aea90517
                Found module libxcb-shm.so.0 with build-id: edb24ef4079aa423edcc50a3bb0dfb912fe8a57a
                Found module libpng16.so.16 with build-id: d58bf7c11ac793d528926238d831792b5ef792cf
                Found module libfreetype.so.6 with build-id: e3aff1d56fb1aecc723a73882f7d0f208a36c4bc
                Found module libpixman-1.so.0 with build-id: 5e936cdac032b6048d9d1a8c0bb0e4a10c86d48c
                Found module libthai.so.0 with build-id: afa54530349e68380815d606d15dbfda8952799f
                Found module libselinux.so.1 with build-id: 6fa53202ce676297de24873c886443b2759bfd8a
                Found module libmount.so.1 with build-id: eeb33f2b4b9c3eb0a29575eb9932ef08663bd836
                Found module libz.so.1 with build-id: 30840b79ac329ecbf1dec0bb60180eed256d319f
                Found module libXext.so.6 with build-id: 9fb1880e02dfa11a8c39cd1a170109de08302059
                Found module libwayland-client.so.0 with build-id: a85980f4efa33fa5cadfbf257349fef99d499427
                Found module libwayland-egl.so.1 with build-id: e13dfac5961e8fb58c54984fe8110a73c2f5ef99
                Found module libwayland-cursor.so.0 with build-id: abcd1ab467757354ac36fd0938b82d47d7aebe1f
                Found module libxkbcommon.so.0 with build-id: a4b17d939092101dc8f6b2a1d70eaf1fddb2dd51
                Found module libXdamage.so.1 with build-id: 8358b7625700dc247fa21fb4304cba877a28bb04
                Found module libXcomposite.so.1 with build-id: 2c84db5342304ba1a76db7dd9b7a3bfaa8a716ce
                Found module libXcursor.so.1 with build-id: d936a5db46d8babb0f2cc490df36b6b18a16d8aa
                Found module libXrandr.so.2 with build-id: 069f930a2b41f3908a1a92b1a51c38bd13a559e2
                Found module libXinerama.so.1 with build-id: 9823bebfa26a681265db4aeb09abf44deec38401
                Found module libfontconfig.so.1 with build-id: 0bb435fdd5ec37178e14ea03bb36f779a4b72a94
                Found module libharfbuzz.so.0 with build-id: 3b9c495c079286b8d1f55d0937a0a771593eb7e6
                Found module libpangoft2-1.0.so.0 with build-id: a7dd79c7ea8ec4d5791f83f9a8f34ffbfa8c3801
                Found module libepoxy.so.0 with build-id: 5ea53a2b100e4b044eee19d5222881a724abf046
                Found module libatk-bridge-2.0.so.0 with build-id: 7e8009077fbdcd7bf094c51bf78742b96f216d73
                Found module libcairo-gobject.so.2 with build-id: 71b5bd37d77ea1862d2ed00e9f6ead482f307db8
                Found module libXfixes.so.3 with build-id: a9c550a40b8154a3b4b5e2ac182bb50c013c3f18
                Found module libXi.so.6 with build-id: 8ff5a3ac871a90fd9d0a7917c61f748a41c6b5ee
                Found module libX11.so.6 with build-id: b8d9314a7185312e4813abcac67d8b68ae2fd690
                Found module libpangocairo-1.0.so.0 with build-id: cb231e62ccba07e561d1d08804e975f615a6faf6
                Found module libgmodule-2.0.so.0 with build-id: 991a9f61e69c30ef8ab73761c300ae51249ede63
                Found module libgdk_pixbuf-2.0.so.0 with build-id: 374b383e3b68b5d8b552519094129f401596e502
                Found module libatk-1.0.so.0 with build-id: b93088667fbd06f6b72d273403d352e7c0554698
                Found module libc.so.6 with build-id: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d
                Found module libgcc_s.so.1 with build-id: 09c4935b79388431a1248f6a98e00d7dc81b8513
                Found module libm.so.6 with build-id: 27e82301dba6c3f644404d504e1bb1c97894b433
                Found module libstdc++.so.6 with build-id: f57e02bfadacc0c923c82457d5e18e1830b5faea
                Found module libsigc-2.0.so.0 with build-id: e5769fe6e782b354e32316abb6ab11f0df1fa35d
                Found module libglib-2.0.so.0 with build-id: 137458a0f7846a084270bf5bb03df075a578db6d
                Found module libgobject-2.0.so.0 with build-id: 44f60e584780daaeb1880ead5dd00f12ffd423d2
                Found module libglibmm-2.4.so.1 with build-id: 1578de9c248e58bed0f7cf4187a3d9808f5455e4
                Found module libvte-2.91.so.0 with build-id: fa3d2eda3dc3b7fb86aad1358865f396c8ca948f
                Found module libfmt.so.8 with build-id: 1a50cf7c320e3ffcb933ec2c05701af5770b2f09
                Found module libfribidi.so.0 with build-id: 6e075a666e1da8ffdb948d734e75d82b1b6dc0fb
                Found module libuchardet.so.0 with build-id: 704ad2edddc3e36ae339753f7bdf978dc317d7ec
                Found module libcurl.so.4 with build-id: 80b7b8bd1eee0cf5f46067c9e48534e4f33d8778
                Found module libsqlite3.so.0 with build-id: 0f2f07c3459119c3759ed803ccf46906be78bee4
                Found module libxml2.so.2 with build-id: 2025ebcf5a6f422d82bdf345647c746def8ecaa2
                Found module libxml++-2.6.so.2 with build-id: 5a8c77cdc502a2f01b1ebb01b4b48154e2315ca9
                Found module libgspell-1.so.2 with build-id: 7f7395d5b064b9711b4b00744bdd9f3daaf43461
                Found module libgtksourceviewmm-3.0.so.0 with build-id: ed141c4f95aee114f86da2273e210f8368bd602b
                Found module libcairo.so.2 with build-id: 60a39c3684e41370bd0a59ed1ecbdccf47e30069
                Found module libpango-1.0.so.0 with build-id: 2d778a30dd59c0673b0208c538999ccc0991093a
                Found module libcairomm-1.0.so.1 with build-id: 11f5c2097449e061d2b146ff999419fa9ca9d5a9
                Found module libpangomm-1.4.so.1 with build-id: 7392a28f5a06ad125c179695b3741331510330d7
                Found module libgio-2.0.so.0 with build-id: 9b52271b63917542ba10ffb8a82b97befd2c238f
                Found module libgdk-3.so.0 with build-id: 97b768ef80858a79741be2492754d948989e63c6
                Found module libgtk-3.so.0 with build-id: 9a340345f5e200f42140f3cb4bacb407e91843f8
                Found module libgiomm-2.4.so.1 with build-id: 918b5b4c39950f4e5079fb4f8b84dd40861a9761
                Found module libgdkmm-3.0.so.1 with build-id: 4560ccdfcd1656760dfad9edeb5dbc97a0371fa1
                Found module libatkmm-1.6.so.1 with build-id: fd4e19a710a00de0c4359b06ae988fd606f5162a
                Found module libgtkmm-3.0.so.1 with build-id: 0493b27573bb4799bbc54ebb50f0aa67f514910e
                Found module cherrytree with build-id: 1ea138017a1e0c63ed056d4db0c51c4bbdad31d8
                Stack trace of thread 62084:
                #0  0x00007fd8dea7ba7c __pthread_kill_implementation (libc.so.6 + 0x96a7c)
                #1  0x00007fd8dea27476 __GI_raise (libc.so.6 + 0x42476)
                #2  0x00007fd8dea0d7f3 __GI_abort (libc.so.6 + 0x287f3)
                #3  0x00007fd8dedb6bbe n/a (libstdc++.so.6 + 0xa2bbe)
                #4  0x00007fd8dedc224c n/a (libstdc++.so.6 + 0xae24c)
                #5  0x00007fd8dedc22b7 _ZSt9terminatev (libstdc++.so.6 + 0xae2b7)
                #6  0x00007fd8dedc2518 __cxa_throw (libstdc++.so.6 + 0xae518)
                #7  0x00007fd8e04bb8a5 _ZN3Gio5Error10throw_funcEP7_GError (libgiomm-2.4.so.1 + 0xc88a5)
                #8  0x00007fd8df13d268 _ZN4Glib5Error15throw_exceptionEP7_GError (libglibmm-2.4.so.1 + 0x5a268)
                #9  0x00007fd8e04d0d9e _ZN3Gio11Application20register_applicationEv (libgiomm-2.4.so.1 + 0xddd9e)
                #10 0x0000557e73e7edd6 _ZN5CtAppC1EN4Glib7ustringE (cherrytree + 0x141dd6)
                #11 0x0000557e73e7eef3 _ZN5CtApp6createEN4Glib7ustringE (cherrytree + 0x141ef3)
                #12 0x0000557e73e489cb main (cherrytree + 0x10b9cb)
                #13 0x00007fd8dea0ed90 __libc_start_call_main (libc.so.6 + 0x29d90)
                #14 0x00007fd8dea0ee40 __libc_start_main_impl (libc.so.6 + 0x29e40)
                #15 0x0000557e73e642c5 _start (cherrytree + 0x1272c5)
                
                Stack trace of thread 62086:
                #0  0x00007fd8deafdd7f __GI___poll (libc.so.6 + 0x118d7f)
                #1  0x00007fd8deff3666 n/a (libglib-2.0.so.0 + 0xaa666)
                #2  0x00007fd8def9c3e3 g_main_context_iteration (libglib-2.0.so.0 + 0x533e3)
                #3  0x00007fd8def9c431 n/a (libglib-2.0.so.0 + 0x53431)
                #4  0x00007fd8defcda51 n/a (libglib-2.0.so.0 + 0x84a51)
                #5  0x00007fd8dea79b43 start_thread (libc.so.6 + 0x94b43)
                #6  0x00007fd8deb0ba00 __clone3 (libc.so.6 + 0x126a00)
                
                Stack trace of thread 62087:
                #0  0x00007fd8deafdd7f __GI___poll (libc.so.6 + 0x118d7f)
                #1  0x00007fd8deff3666 n/a (libglib-2.0.so.0 + 0xaa666)
                #2  0x00007fd8def9e2b3 g_main_loop_run (libglib-2.0.so.0 + 0x552b3)
                #3  0x00007fd8df9fe04a n/a (libgio-2.0.so.0 + 0x11504a)
                #4  0x00007fd8defcda51 n/a (libglib-2.0.so.0 + 0x84a51)
                #5  0x00007fd8dea79b43 start_thread (libc.so.6 + 0x94b43)
                #6  0x00007fd8deb0ba00 __clone3 (libc.so.6 + 0x126a00)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 62084]
[New LWP 62086]
[New LWP 62087]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cherrytree --new_window'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140569362763008) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd8daef0d00 (LWP 62084))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 62084]
[New LWP 62086]
[New LWP 62087]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cherrytree --new_window'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140569362763008) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd8daef0d00 (LWP 62084))]
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140569362763008) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140569362763008) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140569362763008, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fd8dea27476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fd8dea0d7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fd8dedb6bbe in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fd8dedc224c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fd8dedc22b7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fd8dedc2518 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fd8e04bb8a5 in Gio::Error::throw_func(_GError*) () from /lib/x86_64-linux-gnu/libgiomm-2.4.so.1
#10 0x00007fd8df13d268 in Glib::Error::throw_exception(_GError*) () from /lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#11 0x00007fd8e04d0d9e in Gio::Application::register_application() () from /lib/x86_64-linux-gnu/libgiomm-2.4.so.1
#12 0x0000557e73e7edd6 in CtApp::CtApp(Glib::ustring) ()
#13 0x0000557e73e7eef3 in CtApp::create(Glib::ustring) ()
#14 0x0000557e73e489cb in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 62084]
[New LWP 62086]
[New LWP 62087]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cherrytree --new_window'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140569362763008) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd8daef0d00 (LWP 62084))]

Thread 3 (Thread 0x7fd8da045640 (LWP 62087)):
#0  0x00007fd8deafdd7f in __GI___poll (fds=0x557e74b13f10, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd8deff3666 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd8def9e2b3 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd8df9fe04a in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007fd8defcda51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd8dea79b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140733381415776, 8879711170138965057, 140569347380800, 11, 140569425188944, 140733381416128, -8896115270088424383, -8896105647730228159}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fd8deb0ba00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 2 (Thread 0x7fd8da846640 (LWP 62086)):
#0  0x00007fd8deafdd7f in __GI___poll (fds=0x557e74b09360, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd8deff3666 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd8def9c3e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd8def9c431 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fd8defcda51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd8dea79b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140733381415488, 8879711170138965057, 140569355773504, 0, 140569425188944, 140733381415840, -8896114171113667519, -8896105647730228159}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007fd8deb0ba00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 1 (Thread 0x7fd8daef0d00 (LWP 62084)):
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140569362763008) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7fd8daef0d00
        old_mask = {__val = {0, 0, 0, 0, 0, 0, 2, 9223372036854775822, 0, 0, 0, 0, 0, 0, 2, 9223372036854775822}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140569362763008) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=140569362763008, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007fd8dea27476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007fd8dea0d7f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xd68, sa_sigaction = 0xd68}, sa_mask = {__val = {2, 140569426785952, 3432, 140569429665732, 140569425152080, 2, 140569425152080, 10, 17199126140712677888, 2, 18446744073709551424, 0, 94001612396544, 2, 94001612396544, 94001612880160}}, sa_flags = 188032640, sa_restorer = 0x557e740cca20 <typeinfo name for Gio::Error>}
        sigs = {__val = {32, 0, 0, 0, 10, 114, 140569428641920, 140733381420288, 0, 140569425713796, 0, 2, 140569429665732, 2, 94001612880160, 140569425149805}}
#5  0x00007fd8dedb6bbe in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007fd8dedc224c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x00007fd8dedc22b7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#8  0x00007fd8dedc2518 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#9  0x00007fd8e04bb8a5 in Gio::Error::throw_func(_GError*) () from /lib/x86_64-linux-gnu/libgiomm-2.4.so.1
No symbol table info available.
#10 0x00007fd8df13d268 in Glib::Error::throw_exception(_GError*) () from /lib/x86_64-linux-gnu/libglibmm-2.4.so.1
No symbol table info available.
#11 0x00007fd8e04d0d9e in Gio::Application::register_application() () from /lib/x86_64-linux-gnu/libgiomm-2.4.so.1
No symbol table info available.
#12 0x0000557e73e7edd6 in CtApp::CtApp(Glib::ustring) ()
No symbol table info available.
#13 0x0000557e73e7eef3 in CtApp::create(Glib::ustring) ()
No symbol table info available.
#14 0x0000557e73e489cb in main ()
No symbol table info available.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140569362763008) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140569362763008) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140569362763008, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fd8dea27476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fd8dea0d7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fd8dedb6bbe in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fd8dedc224c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fd8dedc22b7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fd8dedc2518 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fd8e04bb8a5 in Gio::Error::throw_func(_GError*) () from /lib/x86_64-linux-gnu/libgiomm-2.4.so.1
#10 0x00007fd8df13d268 in Glib::Error::throw_exception(_GError*) () from /lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#11 0x00007fd8e04d0d9e in Gio::Application::register_application() () from /lib/x86_64-linux-gnu/libgiomm-2.4.so.1
#12 0x0000557e73e7edd6 in CtApp::CtApp(Glib::ustring) ()
#13 0x0000557e73e7eef3 in CtApp::create(Glib::ustring) ()
#14 0x0000557e73e489cb in main ()
```
Thank you.

**Comment by ajaxStardust** [comment]
Do you use the "Always on Top" feature at all? Pin-to-top (whatever exact name). I've had it freeze like that in a similar manner on Windows, in some sequence of things associated w/ that feature. Funny. I think I'm the one who told him to add it. haha. Oh i'm a jerk. I think you can get Pin-to-top to function without crashing it but i forget-- don't feel like trying to rem (at the moment at least, or i'd share for posterity)-- and rarely mess with it for that reason. 

CherryTree still rocks though of course. :)

**Comment by firepainting** [comment]
To be honest I think the culprit here--and this is pure speculation--is Cryptomator. In March and April my two PC's had this same issue, one instance on each.

Last May I ditched Cryptomator and have been using another enryption tool and I have never encountered this issue again.

Closing this issue now. Thank you!
