### ISSUE TITLE
[0.38.100] TypeError: ord() expected a character, but string of length 2 found

### ISSUE THREAD

**Issue by piyo-gh** [giuspen/cherrytree#224]
If I enable word count in statusbar, I have a lot of error in cherrytree.exe.log file.
I'm using Japanese caracters.

```
Traceback (most recent call last):
  File "core.pyc", line 4871, in on_sourceview_event_after
  File "support.pyc", line 270, in on_sourceview_event_after_key_release
  File "core.pyc", line 4912, in update_selected_node_statusbar_info
  File "core.pyc", line 4928, in get_word_count
  File "wordbreak.pyc", line 206, in break_units
  File "wordbreak.pyc", line 133, in word_breakables
  File "wordbreak.pyc", line 235, in _preprocess_boundaries
  File "wordbreak.pyc", line 288, in word_break
  File "wordbreak.pyc", line 292, in _word_break
TypeError: ord() expected a character, but string of length 2 found
```

```
Traceback (most recent call last):
  File "core.pyc", line 2993, in on_node_changed
  File "core.pyc", line 4912, in update_selected_node_statusbar_info
  File "core.pyc", line 4928, in get_word_count
  File "wordbreak.pyc", line 206, in break_units
  File "wordbreak.pyc", line 133, in word_breakables
  File "wordbreak.pyc", line 235, in _preprocess_boundaries
  File "wordbreak.pyc", line 288, in word_break
  File "wordbreak.pyc", line 292, in _word_break
TypeError: ord() expected a character, but string of length 2 found
```

Windows 10 x64

**Comment by giuspen** [comment]
This has been addressed in https://github.com/giuspen/cherrytree/commit/0bda8ea67d7d9cb142f375b5bc83bf01cc141878
