### ISSUE TITLE
[PowerPC] Segfault on launch: `KERN_PROTECTION_FAILURE at address: 0x00000014`

### ISSUE THREAD

**Issue by barracuda156** [giuspen/cherrytree#2518]
**Version, Operative system**
macOS 10.6 / ppc

**Describe the bug**
The binary segfaults on launch:
```
cherrytree(47891) malloc: *** error for object 0x45b3034: Non-aligned pointer being freed
*** set a breakpoint in malloc_error_break to debug
cherrytree(47891) malloc: *** error for object 0x45b30a4: Non-aligned pointer being freed
*** set a breakpoint in malloc_error_break to debug

** (process:47891): WARNING **: 20:41:46.566: locale::facet::_S_create_c_locale name not valid

Reading symbols for shared libraries .. done

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x00000014
0x0001339c in spdlog::logger::log<char const*> ()
(gdb) bt
#0  0x0001339c in spdlog::logger::log<char const*> ()
#1  0x8fe33c48 in __dyld_error_string ()
#2  0x00014864 in glib_log_handler ()
#3  0x0270a76c in g_logv ()
#4  0x0270a8d8 in g_log ()
#5  0x0263bbec in Glib::Class::register_derived_type ()
#6  0x0216993c in Gsv::StyleSchemeChooser_Class::init ()
#7  0x02169e0c in Gsv::StyleSchemeChooser::get_type ()
#8  0x0216eaa8 in Gsv::wrap_init ()
#9  0x0216eaf8 in Gsv::init ()
#10 0x000bc6f4 in CtApp::CtApp ()
#11 0x000bcb38 in CtApp::create ()
#12 0x006461d4 in main ()
```

**To Reproduce**
Assuming MacPorts is installed on a PowerPC MacOS,
```
sudo port install cherrytree
cherrytree
```

**Comment by giuspen** [comment]
I did apply a couple of changes and I am going to release a new version v1.1.3 in a few days, if it happens again with the new version please provide the new crash backtrace

**Comment by barracuda156** [comment]
@giuspen Thank you! I will try that then.

**Comment by barracuda156** [comment]
@giuspen Hi, any chance to look at the issue again?

**Comment by barracuda156** [comment]
@giuspen Quick update:

1. The bug is not resolved in 1.6.3.
2. However, building with bundled libfmt/spdlog (which is a non-default choice) allows the app to launch normally.
