### ISSUE TITLE
ImportError import builtins on RedHat7.3

### ISSUE THREAD

**Issue by rodrigcj** [giuspen/cherrytree#257]
I am having trouble running cherrytree on RedHat 7.3. The error that presents:
[Myuser @ mypc cherrytree-0.38.1] $ cherrytree
Traceback (most recent call last):
   File "/ usr / bin / cherrytree", line 78, in <module>
     F_main (args)
   File "/ usr / bin / cherrytree", line 49, in f_main
     Import main
   File "/usr/share/cherrytree/modules/main.py", line 31, in <module>
     Import builtins
ImportError: No module named builtins

Does anyone know this error? Or how to solve it.
Thank you.

**Comment by giuspen** [comment]
Are you running with python2?

**Comment by rodrigcj** [comment]
Yep.
[Myuser@mypc ~]$ python -V
Python 2.7.5
[Myuser@mypc ~]$

**Comment by bakbuk** [comment]
Did you try 'pip install future'?
