### ISSUE TITLE
cherrytree wont start if started from desktop icon

### ISSUE THREAD

**Issue by r3k2** [giuspen/cherrytree#290]
Using plasma desktop if I go to the menu and click on the cherry it wont start..
if I open a konsole and type cherrytree then starts fine.. but is a pain to have the konsole window open all the time

**Comment by ChrisFernandez** [comment]
I was always to catch the error by forcing it to run on a konsole and so not close the terminal after the app run.
```
(process:7912): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.

(cherrytree:7912): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(cherrytree:7912): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Traceback (most recent call last):
  File "/bin/cherrytree", line 78, in <module>
    f_main(args)
  File "/bin/cherrytree", line 50, in f_main
    main.main(args)
  File "/usr/share/cherrytree/modules/main.py", line 232, in main
    lang_str = initializations()
  File "/usr/share/cherrytree/modules/main.py", line 161, in initializations
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by ChrisFernandez** [comment]
ok so found a workaround..
![workaround-cherrytree](https://user-images.githubusercontent.com/5316229/31426234-4e6c1af4-ae17-11e7-91e4-bdfcad3a5551.png)

all my system works fine.. all other apps and python apps.. my locales are setup ok..
so not sure why for cherrytree I have to force the app to get the env variable.

**Comment by giuspen** [comment]
Hi Chris, what linux distribution is running plasma?
what do you get in the terminal if you type "export | grep LANG"?

**Comment by ChrisFernandez** [comment]
@giuspen I am running Arch GNU/Linux and my locales are setup right I tripple check this is why every other app is working fine.
```
$ locale -a
C
en_US.utf8
es_ES
es_ES@euro
es_ES.iso88591
es_ES.iso885915@euro
es_ES.utf8
POSIX
spanish
```
```
env | grep LC
LC_ALL=es_ES.utf8
LC_MEASUREMENT=es_ES.US-ASCII
LC_MONETARY=en_US.US-ASCII
LC_COLLATE=es_ES.US-ASCII
LC_NUMERIC=es_ES.US-ASCII
LC_TIME=es_ES.US-ASCII
```

**Comment by ChrisFernandez** [comment]
```
env | grep LANG
LANG=es_ES.utf8
LANGUAGE=es
```
```
locale -a
C
en_US.utf8
es_ES
es_ES@euro
es_ES.iso88591
es_ES.iso885915@euro
es_ES.utf8
POSIX
spanish
```

**Comment by giuspen** [comment]
Would you be able to test a version from github? I don't know how to package for Arch

**Comment by giuspen** [comment]
I just committed, please let me know the behaviour

**Comment by ChrisFernandez** [comment]
hey sorry took some time, busy with work.. 
going to create a arch package now and try. thanks

**Comment by ayushbindlish** [comment]
I am still having the same issue. Though the workaround by r3k2 for setting the locale works.

**Comment by txe** [comment]
@ayushbindlish, 
Can you try 0.99 version instead of 0.39? You can download it from https://www.giuspen.com/cherrytree/#testing

**Comment by ayushbindlish** [comment]
> @ayushbindlish,
> Can you try 0.99 version instead of 0.39? You can download it from https://www.giuspen.com/cherrytree/#testing

I am using 0.99 and still the same issue. Had to use r3k2 workaround to make it work.

**Comment by txe** [comment]
@ayushbindlish, can you say what os/DE are you using? I'll try to reproduce the issue.

**Comment by ayushbindlish** [comment]
@txe I am using Kali 2020.3
