### ISSUE TITLE
ValueError: unknown locale: en_IL

### ISSUE THREAD

**Issue by pantos27** [giuspen/cherrytree#368]
Getting this error on Ubuntu 18.04 after a fresh install
Worked on 17.10

```
Gtk-Message: 17:12:32.438: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/usr/bin/cherrytree", line 72, in <module>
    f_main(args)
  File "/usr/bin/cherrytree", line 49, in f_main
    import main
  File "/usr/share/cherrytree/modules/main.py", line 30, in <module>
    import cons, core
  File "/usr/share/cherrytree/modules/core.py", line 24, in <module>
    import cons, menus, support, config, machines, clipboard, imports, exports, printing, tablez, lists, findreplace, codeboxes, ctdb
  File "/usr/share/cherrytree/modules/support.py", line 23, in <module>
    import cons, config, exports
  File "/usr/share/cherrytree/modules/config.py", line 45, in <module>
    SPELL_CHECK_LANG_DEFAULT = locale.getdefaultlocale()[0]
  File "/usr/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: en_IL

```

**Comment by giuspen** [comment]
please try and run the development version [](https://www.giuspen.com/cherrytree/#dev)

**Comment by pantos27** [comment]
Yeah, that works.
Only shows this message and then opens the app
`Failed to load module "canberra-gtk-module"`

Thanks
