### ISSUE TITLE
Crash when searching in all nodes

### ISSUE THREAD

**Issue by thesteveyyy** [giuspen/cherrytree#375]
I have the problem that CherryTree always crashes when searching in all nodes. It can still be seen in the log that this is a memory error. The effect is reproducible under Windows 10 and Linux (Ubuntu 16.4). Since CherryTree has been my 'second brain' for a long time, the amount of data (including many screenshots) is quite large (currently about 435MB). 
Is it possible to change the search procedure so that memory consumption does not increase continuously during the search execution? My Python knowledge is unfortunately close to zero, so I can't make a quick assessment myself.
Here are the last log entries before the crash:

Traceback (most recent call last):
  File "core.pyc", line 3216, in find_in_all_nodes
  File "findreplace.pyc", line 475, in find_in_all_nodes
  File "findreplace.pyc", line 793, in parse_given_node_content
  File "findreplace.pyc", line 793, in parse_given_node_content
  File "findreplace.pyc", line 777, in parse_given_node_content
  File "core.pyc", line 3113, in get_textbuffer_from_tree_iter
  File "ctdb.pyc", line 537, in read_db_node_content
MemoryError

By the way, I use the latest version 0.38.4
Thank you!

**Comment by giuspen** [comment]
I'm looking forward to improve the memory usage with the ongoing porting to gtkmm3

**Comment by talicz** [comment]
I am having the same issue with versions cherrytree (0.37.6-1.1) and cherrytree (0.38.8-0).

**Comment by TomNUE** [comment]
Same problem with last testing version 0.99.5 on Linux Mint 20 Cinnamon. Keep the fingers crossed, that its fixable with less effort

**Comment by txe** [comment]
If you describe how to reproduce your problem, then I can fix it.

**Comment by TomNUE** [comment]
Just clicking on the Button: search in all nodes (using in German, in allen Knoten suchen). After typing the search-criteria and click on Enter Cherrytree is closed

**Comment by giuspen** [comment]
Could you create a test cherrytree document where you can reproduce the issue, share it with us and tell what to search for?

**Comment by UrfinJuice11** [comment]
Still no solution? The same issue on Windows 10. With Cherry 0.99.30 and Kali Linux the same Cherry verion.

**Comment by giuspen** [comment]
You must try the latest before claiming that there is a bug. The latest is 0.99.38. If the bug is still there and you help me reproduce providing data I will fix it.
