### ISSUE TITLE
Search and timestamp not work

### ISSUE THREAD

**Issue by DoubleK66** [giuspen/cherrytree#395]
I installed cherrytree on Mac thru Mac ports, it is working fine except cannot Search or insert a timestamp, even if I run as a remote application from an Ubuntu, it will have same error but the same copy run locally on the Ubuntu is alright

_When try to search_ 
```
Traceback (most recent call last):
  File "/Users/X/myapps/cherrytree-0.38.5/modules/core.py", line 3228, in find_in_all_nodes
    self.find_handler.find_in_all_nodes(None)
  File "/Users/X/myapps/cherrytree-0.38.5/modules/findreplace.py", line 432, in find_in_all_nodes
    pattern = self.dialog_search(title, self.replace_active, True, True)
  File "/Users/X/myapps/cherrytree-0.38.5/modules/findreplace.py", line 191, in dialog_search
    ts_label = support.get_timestamp_str(ts_format, self.search_replace_dict['ts_cre_>'][1])
  File "/Users/X/myapps/cherrytree-0.38.5/modules/support.py", line 40, in get_timestamp_str
    timestamp_str = time.strftime(config.TIMESTAMP_FORMAT_DEFAULT, struct_time).decode(locale.getlocale()[1])
TypeError: decode() argument 1 must be string, not None
```

_When try to insert timestamp_
```
Traceback (most recent call last):
  File "/Users/X/myapps/cherrytree-0.38.5/modules/core.py", line 5083, in timestamp_insert
    timestamp = support.get_timestamp_str(self.timestamp_format, time.time())
  File "/Users/X/myapps/cherrytree-0.38.5/modules/support.py", line 40, in get_timestamp_str
    timestamp_str = time.strftime(config.TIMESTAMP_FORMAT_DEFAULT, struct_time).decode(locale.getlocale()[1])
TypeError: decode() argument 1 must be string, not None
```
Anyone have same problem?

**Comment by 41eck** [comment]
I have this problem on Arch Linux too.

**Comment by 41eck** [comment]
@giuspen English and locales are
  en_US.UTF-8... 
  en_US.ISO-8859-1...

**Comment by giuspen** [comment]
Could you try to run the latest code from git?
