### ISSUE TITLE
Error when I close CherryTree (log file inc.)

### ISSUE THREAD

**Issue by UnluckyLuke** [giuspen/cherrytree#406]
Running:
Windows 10 Home 64-bit.
CherryTree 0.38.5

When closing down the application I get a error-message which only shows up sometimes, I cant recall exactly what it said but it tells me to check the log file, and this is what's found in the log file:

################### Log Start:
`Traceback (most recent call last):

  File "core.pyc", line 3030, in on_node_changed

  File "core.pyc", line 4658, in spell_check_set_on

  File "core.pyc", line 4668, in spell_check_reload_on_buffer

  File "pgsc_spellcheck.pyc", line 230, in buffer_initialize

ValueError: The tag is already in a tag table

Traceback (most recent call last):

  File "core.pyc", line 3030, in on_node_changed

  File "core.pyc", line 4658, in spell_check_set_on

  File "core.pyc", line 4668, in spell_check_reload_on_buffer

  File "pgsc_spellcheck.pyc", line 230, in buffer_initialize

ValueError: The tag is already in a tag table

Traceback (most recent call last):

  File "core.pyc", line 3030, in on_node_changed

  File "core.pyc", line 4658, in spell_check_set_on

  File "core.pyc", line 4668, in spell_check_reload_on_buffer

  File "pgsc_spellcheck.pyc", line 230, in buffer_initialize

ValueError: The tag is already in a tag table

Traceback (most recent call last):

  File "main.pyc", line 105, in on_window_destroy_event

  File "shutil.pyc", line 239, in rmtree

  File "shutil.pyc", line 237, in rmtree

WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\USERX\\appdata\\local\\temp\\tmpe_tknl/*.*'

Traceback (most recent call last):

  File "main.pyc", line 105, in on_window_destroy_event

  File "shutil.pyc", line 239, in rmtree

  File "shutil.pyc", line 237, in rmtree

WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\USERX\\appdata\\local\\temp\\tmpesiu0m/*.*'

Traceback (most recent call last):

  File "main.pyc", line 105, in on_window_destroy_event

  File "shutil.pyc", line 239, in rmtree

  File "shutil.pyc", line 237, in rmtree

WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\USERX\\appdata\\local\\temp\\tmpz9uj2k/*.*'

Traceback (most recent call last):

  File "main.pyc", line 105, in on_window_destroy_event

  File "shutil.pyc", line 239, in rmtree

  File "shutil.pyc", line 237, in rmtree

WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\USERX\\appdata\\local\\temp\\tmptxf6sb/*.*'

Traceback (most recent call last):

  File "main.pyc", line 105, in on_window_destroy_event

  File "shutil.pyc", line 239, in rmtree

  File "shutil.pyc", line 237, in rmtree

WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\USERX\\appdata\\local\\temp\\tmppcx6sq/*.*'

Traceback (most recent call last):

  File "main.pyc", line 105, in on_window_destroy_event

  File "shutil.pyc", line 239, in rmtree

  File "shutil.pyc", line 237, in rmtree

WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\USERX\\appdata\\local\\temp\\tmpydgjmy/*.*'

Traceback (most recent call last):

  File "main.pyc", line 105, in on_window_destroy_event

  File "shutil.pyc", line 239, in rmtree

  File "shutil.pyc", line 237, in rmtree

WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\USERX\\appdata\\local\\temp\\tmp7ish8e/*.*'

Traceback (most recent call last):

  File "main.pyc", line 105, in on_window_destroy_event

  File "shutil.pyc", line 239, in rmtree

  File "shutil.pyc", line 237, in rmtree

WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\USERX\\appdata\\local\\temp\\tmptdrntp/*.*'
`
################### Log End

Any ideas what's causing all this?

**Comment by giuspen** [comment]
I'm going to release soon 0.38.6 where this error should not happen anymore
