### ISSUE TITLE
Find into All the Tree Nodes Contents fails

### ISSUE THREAD

**Issue by StrangeDaize** [giuspen/cherrytree#412]
When clicking the magnifying glass on the current build, the following error occurs:

Traceback (most recent call last):
  File "/home/Downloads/cherrytree/modules/core.py", line 3026, in on_node_changed
    self.update_selected_node_statusbar_info()
  File "/home/Downloads/cherrytree/modules/core.py", line 4977, in update_selected_node_statusbar_info
    timestamp_creation = support.get_timestamp_str(self.timestamp_format, ts_creation)
  File "/home/Downloads/cherrytree/modules/support.py", line 44, in get_timestamp_str
    timestamp_str = time.strftime(config.TIMESTAMP_FORMAT_DEFAULT, struct_time).decode(encoding)
TypeError: decode() argument 1 must be string, not None
Traceback (most recent call last):
  File "/home/Downloads/cherrytree/modules/core.py", line 3228, in find_in_all_nodes
    self.find_handler.find_in_all_nodes(None)
  File "/home/Downloads/cherrytree/modules/findreplace.py", line 432, in find_in_all_nodes
    pattern = self.dialog_search(title, self.replace_active, True, True)
  File "/home/Downloads/cherrytree/modules/findreplace.py", line 191, in dialog_search
    ts_label = support.get_timestamp_str(ts_format, self.search_replace_dict['ts_cre_>'][1])
  File "/home/Downloads/cherrytree/modules/support.py", line 44, in get_timestamp_str
    timestamp_str = time.strftime(config.TIMESTAMP_FORMAT_DEFAULT, struct_time).decode(encoding)
TypeError: decode() argument 1 must be string, not None

**Comment by giuspen** [comment]
What is the lpcale/language that you are using?

**Comment by StrangeDaize** [comment]
LC_ALL=C
LANG=en_US.UTF-8
GDM_LANG=en_US.UTF-8

**Comment by StrangeDaize** [comment]
This may be an issue with python 2.7.5:

[dstrange@dstrange ~]$ python --version
Python 2.7.5
[dstrange@dstrange ~]$ python
Python 2.7.5 (default, May 31 2018, 09:41:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getdefaultlocale()
(None, None)
>>> locale.getlocale()                                                          
(None, None)
>>> quit()
[dstrange@dstrange ~]$ locale
LANG=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C

**Comment by giuspen** [comment]
Could you try the latest from github master?

**Comment by StrangeDaize** [comment]
Confirmed that it resolved the issue.
Much appreciated
