### ISSUE TITLE
segfault when auto saving

### ISSUE THREAD

**Issue by golimarrrr** [giuspen/cherrytree#437]
I've been unable to reproduce it, as it segfaults when autosaving: I modify a note, switch to another application, and after a few seconds I see that CherryTree disappears from the taskbar.
The only log I could get is the segfault line on syslog, is there a CherryTree log file where I can find more info?

`
Dec 18 18:10:27 pc kernel: [982186.299973] cherrytree[31287]: segfault at a ip 00007f17dd63ba2e sp 00007ffc318cfff0 error 4 in libgtk-x11-2.0.so.0.2400.31[7f17dd518000+43c000]
`

`
Linux pc 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
`

**Comment by golimarrrr** [comment]
```
autosave iter
no changes
autosave iter
no changes
autosave iter
no changes
autosave iter
no changes
already running '/home/username/Documents' - 'notes.ctb'
4 run ''
sel node id=1, seq=1
sel node id=22, seq=2
pending_edit_db_node_buff 22
autosave iter
no changes
autosave iter
no changes
autosave iter
write node content, node_id 22 , write_dict {'upd': True, 'buff': True, 'hier': False, 'child': False, 'prop': False}
1548065965.77 1548065962.54 3.22125458717
Segmentation fault

```

**Comment by giuspen** [comment]
If you disable the autosave, edit that node and save manually (Ctrl +S), does it still crash?

**Comment by golimarrrr** [comment]
It hasn't crashed so far, but it's difficult to replicate.
I think it has something to do with having 2 instances of cherrytree, or with this scenario: opening instance A with one file, then instance B with another file, and then closing instance A

**Comment by golimarrrr** [comment]
I managed to get a gdb backtrace, does this help?:

```
#0  0x00007ffff4ec3a2e in gtk_label_set_text () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#1  0x00007ffff6716f75 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff672937d in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff6731bdc in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff6731fbf in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff54edade in ?? () from /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/_gtk.so
#6  0x000055555564f84a in PyEval_EvalFrameEx ()
#7  0x000055555565514f in PyEval_EvalFrameEx ()
#8  0x000055555564d9f5 in PyEval_EvalCodeEx ()
#9  0x0000555555655448 in PyEval_EvalFrameEx ()
#10 0x000055555564d9f5 in PyEval_EvalCodeEx ()
#11 0x0000555555655448 in PyEval_EvalFrameEx ()
#12 0x000055555564d9f5 in PyEval_EvalCodeEx ()
#13 0x000055555566a5be in ?? ()
#14 0x000055555563c0c3 in PyObject_Call ()
#15 0x0000555555680e1e in ?? ()
#16 0x000055555563c0c3 in PyObject_Call ()
#17 0x0000555555659a10 in PyEval_CallObjectWithKeywords ()
#18 0x00007ffff5fef6a9 in _pyglib_handler_marshal () from /usr/lib/libpyglib-2.0-python2.7.so.0
#19 0x00007ffff623c123 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff623b6aa in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff623ba60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff623bd82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff4ecf3b7 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#24 0x00007ffff558349f in ?? () from /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/_gtk.so
#25 0x0000555555654a8f in PyEval_EvalFrameEx ()
#26 0x000055555565514f in PyEval_EvalFrameEx ()
#27 0x000055555565514f in PyEval_EvalFrameEx ()
#28 0x000055555564d9f5 in PyEval_EvalCodeEx ()
#29 0x000055555564d7b9 in PyEval_EvalCode ()
#30 0x000055555567dbff in ?? ()
#31 0x0000555555678b52 in PyRun_FileExFlags ()
#32 0x000055555567869e in PyRun_SimpleFileExFlags ()
#33 0x0000555555629771 in Py_Main ()
#34 0x00007ffff6f182e1 in __libc_start_main (main=0x5555556290a0 <main>, argc=2, argv=0x7fffffffe6b8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe6a8) at ../csu/libc-start.c:291
#35 0x0000555555628f9a in _start ()

```

**Comment by giuspen** [comment]
The thing is that the crash is likely to be an issue of the pygtk2 binding. I'm afraid you'll have to wait for the gtkmm3 version (hopefully before the end of the year)

**Comment by golimarrrr** [comment]
No problem, the crash rarely happens. So should I report it to the gtk or pygtk projects?

**Comment by giuspen** [comment]
Pygtk2 ang Gtk2 are discontinued, for this reason I'm migrating to Gtk3, hopefully before the end of the year the new version will be ready
