### ISSUE TITLE
when i save cherrytree and a error has happening like this:  write failed - tree to xml

### ISSUE THREAD

**Issue by wooyunvip** [giuspen/cherrytree#443]
error:
E:\tools\1-user.ctz write failed - tree to xml

sysinfo:   Microsoft Windows 10 Pro x64
cherrytree version: CherryTree 0.38.7

cherrytree.exe.log:

Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2516, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '0, 0.75'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2521, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '0, 0.05'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2521, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '0, 0.05'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2521, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '0, 0.05'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2521, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '0, 0.05'
Traceback (most recent call last):
  File "clipboard.pyc", line 431, in to_image
AttributeError: 'NoneType' object has no attribute 'link'
Traceback (most recent call last):
  File "clipboard.pyc", line 431, in to_image
AttributeError: 'NoneType' object has no attribute 'link'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2516, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '0, 0.8'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2521, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '58, 0.98'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2521, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '58, 0.98'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2521, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '58, 0.98'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2516, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '57, 0.8'
Traceback (most recent call last):
  File "clipboard.pyc", line 335, in to_html
  File "imports.pyc", line 2798, in get_clipboard_selection_xml
  File "imports.pyc", line 2825, in boot_n_feed
  File "HTMLParser.pyc", line 117, in feed
  File "HTMLParser.pyc", line 161, in goahead
  File "HTMLParser.pyc", line 327, in parse_starttag
  File "imports.pyc", line 2521, in handle_starttag
  File "imports.pyc", line 2475, in get_rgb_gtk_attribute
ValueError: invalid literal for int() with base 10: '0, 0.04'
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1721, in file_write
  File "core.pyc", line 1624, in file_write_low_level
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1721, in file_write
  File "core.pyc", line 1624, in file_write_low_level
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1721, in file_write
  File "core.pyc", line 1624, in file_write_low_level
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1356, in autosave_timer_iter
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1356, in autosave_timer_iter
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1721, in file_write
  File "core.pyc", line 1624, in file_write_low_level
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 3647, in on_window_delete_event
  File "core.pyc", line 3624, in quit_application
  File "core.pyc", line 3631, in quit_application_totally
  File "core.pyc", line 3658, in check_unsaved
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1721, in file_write
  File "core.pyc", line 1624, in file_write_low_level
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1356, in autosave_timer_iter
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1721, in file_write
  File "core.pyc", line 1624, in file_write_low_level
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError

how can fixed it,thank you ！

**Comment by giuspen** [comment]
The top errors seems to be happening after you copy/pasted something from an html page while those at the bottom seem for out of memory, is your db very big?

**Comment by wooyunvip** [comment]
@giuspen I also think that this is a problem with the database（DB size is 40M），so how can  i fixed it

**Comment by giuspen** [comment]
try and use use the SQLite for such large db rather than full XML, so File--Save As and change Storage Type

**Comment by philippHRO** [comment]
Hello,
i'm getting the error "failed to write to disk" with my SQLite file aswell.

**Comment by giuspen** [comment]
@philippHRO is is systematic at every edit of every node? Have you tried to save as XML instead do you get the same error? Is it Windows or Linux?
