### ISSUE TITLE
Import from KeepNote to Cherrytree Fails (html)

### ISSUE THREAD

**Issue by pdejyothin** [giuspen/cherrytree#477]
Cherrytree Version: 0.38.8 (Windows)
KeepNote Version: 0.7.8 (Windows)

I've exported a KeepNote file to HTML and attempted to import this into Cherrytree (Import > From folder of HTML files). After several seconds nothing happens. However, when I close the program, a pop-up display appears with the content:

Errors occurred
See the logfile of 'E:\CherryTree\bin\cherrytree.exe.log' for details'

Upon opening the 'Cherrytree.exe.log' file, the following log entry is added

---
Traceback (most recent call last):
  File "core.pyc", line 1008, in nodes_add_from_html_folder
  File "core.pyc", line 1184, in nodes_add_from_cherrytree_data
  File "machines.pyc", line 108, in dom_to_treestore
  File "xml\dom\minidom.pyc", line 1928, in parseString
  File "xml\dom\expatbuilder.pyc", line 940, in parseString
  File "xml\dom\expatbuilder.pyc", line 223, in parseString
MemoryError
---

**Comment by pdejyothin** [comment]
The same issue and log error also occurs if I use the 'Import> From KeepNote Folder' and attempt to open the KeepNote folder (not the html export as above) of the same content.

**Comment by giuspen** [comment]
I can have a look if you can send me the zipped keepnote folder privately

**Comment by pdejyothin** [comment]
Hi giuspen,

Thank you for replying. What would be the best method of sending you the file privately?

**Comment by giuspen** [comment]
Hi Paul, my mail is in cherrytree help--about dialog, you can attach to a mail or if very big load to your google drive space and share a link with me

**Comment by as-mironov** [comment]
I've just tested import from Keepnote on version 0.99.37 and it's ok.
