### ISSUE TITLE
error writting to disk with ctd XML

### ISSUE THREAD

**Issue by CLAB72** [giuspen/cherrytree#499]
I'm working with the exe compiled under windows 10. My version is 0.38.8.
I'm using *.ctd XML file type.
The issue is I'm writing a "page" and want to save it. It take to quiet long time (about 40 seconds) and an error message appear:
C:\path\to\ctd file write failed - writting to disk.

Log file content :

Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1721, in file_write
  File "core.pyc", line 1624, in file_write_low_level
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1708, in file_write
  File "machines.pyc", line 323, in treestore_to_dom
  File "xml\dom\minidom.pyc", line 61, in toprettyxml
  File "StringIO.pyc", line 271, in getvalue
MemoryError
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1721, in file_write
  File "core.pyc", line 1624, in file_write_low_level

MemoryError

**Comment by CLAB72** [comment]
It is not possible to save changes.
But the ctd file is "erased". It is set to 0 byte on the hdd.
If I try at other time to save the still opened file, it "reset" the backup file ctd~ to 0 byte.
the 3rd time I save the cdt~~ is set to 0 byte and so on.
Byt he way, I'm loosing datas.

**Comment by giuspen** [comment]
I advise if you are failing to write to disk, to select your changes, copy and paste elsewhere (e.g. to office). I thought I added a specific check for the 0 bytes case to do not rotate the backup but it's clearly not working, the problem is I've never been able to reproduce this so I'm patching blindly. I'll have a look once again, if you have a document where the problem appears always and you can share privately with me please send over.

**Comment by CLAB72** [comment]
My document is more than 20 Mb weight and contain images. 
The workaround is to export the part I modified. Then I retore the ~ backup file file, and re-import datas.
I noticed, for exemple, I had 2 documents opened. Then second crashed down. So I close without saving. At this point I was not able to delete the 0 byte file. Windows tells it is still opened. I close the second doc witch close the app. The file is now free to be deleted.
The app show error message inviting to watch the log file.
Traceback is always the same :
Traceback (most recent call last):
  File "core.pyc", line 1585, in file_save
  File "core.pyc", line 1721, in file_write
  File "core.pyc", line 1624, in file_write_low_level
MemoryError

**Comment by CLAB72** [comment]
Hi Guiseppe,
The file than does not work properly is 38 MB weight. 
I can't send it via Gmail.
I tried to add a new node, and I wasn't able to save the file.

The aim for me, is to have the most part of the documentation in the same file.
I choose cheerytree because of its xml format that I'm keeping versions with bazaar.

There is nothing really secret in this file. But I don't want to publish it.
I will try a file transfert service later.

Regards 
Claude



On Mon, 06 May 2019 09:26:32 +0000 (UTC)
Giuseppe <notifications@github.com> wrotE:

> I advise if you are failing to write to disk, to select your changes, copy and paste elsewhere (e.g. to office). I thought I added a specific check for the 0 bytes case to do not rotate the backup but it's clearly not working, the problem is I've never been able to reproduce this so I'm patching blindly. I'll have a look once again, if you have a document where the problem appears always and you can share privately with me please send over. 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/giuspen/cherrytree/issues/499#issuecomment-489560128


-- 
Claude Brulé <claude.brule@gmail.com>

**Comment by giuspen** [comment]
Hi @CLAB72, you can upload to your google drive and share it with me privately
