### ISSUE TITLE
Unable to import from EssentialPIM html file

### ISSUE THREAD

**Issue by Mr-Tuffery** [giuspen/cherrytree#511]
Giuspen
I have found 2 issues here. I am using Win 10 & logged in as standard user. Running installed CherryTree 0.38.8. and portable version
1. When installed Cherrytree errors it is unable to write to cherrytree.exe.log file. Get permission Denied error. If I run as administrator then it works. Maybe log file should be saved in C:\programdata\CherryTree folder.
2. When I import from EssentialPIM html file nothing happens in the program. On exit an error is generated and saved to the log file. See below.
Traceback (most recent call last):
  File "core.pyc", line 986, in nodes_add_from_epim_html_file
  File "imports.pyc", line 2886, in get_cherrytree_xml
  File "imports.pyc", line 2830, in add_folder
WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\username\\appdata\\local\\temp\\tmp4pzvbt\\EPIM/*.*'

The portable version gets the same error but temp folder is different
WindowsError: [Error 3] The system cannot find the path specified: 'c:\\users\\username\\appdata\\local\\temp\\cherrytreeportabletemp\\tmpjatczm\\EPIM/*.*'

**Comment by giuspen** [comment]
I can have a look if you send me your exported html so that I can try and import

**Comment by CostaC** [comment]
Just came across this same issue while migrating from EssentialPIM.

Windows 7
Portable version

Importing as "EssentialPIM HTML file" does nothing. No error, no spinner.
When I exit, dialog box notifies of error.  Log file shows:

`
Traceback (most recent call last):
  File "core.pyc", line 986, in nodes_add_from_epim_html_file
  File "imports.pyc", line 2890, in get_cherrytree_xml
  File "imports.pyc", line 2834, in add_folder
WindowsError: [Error 3] The system cannot find the path specified: 'u:\\temp\\tmpmraxws\\EPIM/*.*'
`

I can import that same file via "Import from HTML file" but all hierarchy is lost (everything imports in one node).


Attached is a (zipped) EssentialPIM exported HTML file for testing.
[epim-export2.zip](https://github.com/giuspen/cherrytree/files/4163628/epim-export2.zip)
