### ISSUE TITLE
Another OpenSuse 15.1 system fail (see output)

### ISSUE THREAD

**Issue by xGWestx** [giuspen/cherrytree#521]
**This is the 4th system it fails with.**
Traceback (most recent call last):
  File "/usr/bin/cherrytree", line 78, in <module>
    f_main(args)
  File "/usr/bin/cherrytree", line 49, in f_main
    import main
  File "/usr/share/cherrytree/modules/main.py", line 24, in <module>
    import dbus
ImportError: No module named dbus

**Comment by giuspen** [comment]
Have you tried to install python-dbus?

**Comment by xGWestx** [comment]
I tried it. Python-dbus is either not the problem or not the only problem.
I figured it out. Perhaps you should inform users.
Cherrytree must be installed from the Suse GNOME repository.
http://download.opensuse.org/repositories/GNOME:/Apps/openSUSE_Leap_15.1/
The version in the Suse distro repo is hopeless.
Even when using the GNOME repo, **python-xml** must be manually installed. It will not go in as a dependency.
