### ISSUE TITLE
Can't Open CherryTree

### ISSUE THREAD

**Issue by python1996** [giuspen/cherrytree#531]
OS:kali linux
CherryTree 0.38.8

CherryTree works well at yesterday and when I quit CherryTree, It has some error message.
Today, I can't open it, and it has some error output, Please help me to solve the problem. Thanks！

ERROR OUTPUT:
Traceback (most recent call last):
  File "/usr/bin/cherrytree", line 78, in <module>
    f_main(args)
  File "/usr/bin/cherrytree", line 50, in f_main
    main.main(args)
  File "/usr/share/cherrytree/modules/main.py", line 248, in main
    CherryTreeHandler(args, lang_str)
  File "/usr/share/cherrytree/modules/main.py", line 83, in __init__
    self.window_open_new(args.filepath, args.node, True, True if args.filepath else False)
  File "/usr/share/cherrytree/modules/main.py", line 88, in window_open_new
    window = core.CherryTree(self.lang_str, filepath, node_name, self, is_startup, is_arg, False)
  File "/usr/share/cherrytree/modules/core.py", line 252, in __init__
    self.file_startup_load(open_with_file, node_name)
  File "/usr/share/cherrytree/modules/core.py", line 1500, in file_startup_load
    self.file_load(os.path.join(self.file_dir, self.file_name))
  File "/usr/share/cherrytree/modules/core.py", line 1998, in file_load
    if self.xml_handler.dom_to_treestore(cherrytree_string, discard_ids=None):
  File "/usr/share/cherrytree/modules/machines.py", line 117, in dom_to_treestore
    self.append_tree_node(dom_iter, tree_father, discard_ids, node_sequence)
  File "/usr/share/cherrytree/modules/machines.py", line 188, in append_tree_node
    self.append_tree_node(child_dom_iter, tree_iter, discard_ids, child_sequence)
  File "/usr/share/cherrytree/modules/machines.py", line 188, in append_tree_node
    self.append_tree_node(child_dom_iter, tree_iter, discard_ids, child_sequence)
  File "/usr/share/cherrytree/modules/machines.py", line 154, in append_tree_node
    elif child_dom_iter.nodeName == "encoded_png": self.image_deserialize(curr_buffer, child_dom_iter, 2)
  File "/usr/share/cherrytree/modules/machines.py", line 250, in image_deserialize
    pixbuf.embfile = base64.b64decode(dom_node.firstChild.data)
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by giuspen** [comment]
Looks like a binary file you attached in the xml is missing. Open the xml document with a text editor, look for encoded_png there should be one with an argument specifying the name of the embedded file while the nested data is missing. You have to remove completely that node. I can try to help on your document but I'm not sure I'll have access to Internet, I'm on holiday by the sea

**Comment by python1996** [comment]
I have delete node, and CherryTree could work now, Thank you very much!  
Have fun with your holiday!   ^-^
