### ISSUE TITLE
GTK error after update to 0.38.9

### ISSUE THREAD

**Issue by Serasar** [giuspen/cherrytree#562]
Just updated to 0.38.9. Get this error:
```
Traceback (most recent call last):
  File "/usr/bin/cherrytree", line 78, in <module>
    f_main(args)
  File "/usr/bin/cherrytree", line 49, in f_main
    import main
  File "/usr/share/cherrytree/modules/main.py", line 42, in <module>
    import cons, core
  File "/usr/share/cherrytree/modules/core.py", line 40, in <module>
    import support
  File "/usr/share/cherrytree/modules/support.py", line 30, in <module>
    import config
  File "/usr/share/cherrytree/modules/config.py", line 1535
    frame_nodes_icons.set_shadow_type(gtk.SHADOW_NONE)    align_nodes_icons = gtk.Alignment()
                                                      ^
SyntaxError: invalid syntax

```

**Comment by Serasar** [comment]
After rebooting it no longer appers, launches normally.
