### ISSUE TITLE
Cannot open .ctb file

### ISSUE THREAD

**Issue by hellrider9** [giuspen/cherrytree#718]
`Traceback (most recent call last):
  File "/usr/bin/cherrytree", line 78, in <module>
    f_main(args)
  File "/usr/bin/cherrytree", line 50, in f_main
    main.main(args)
  File "/usr/share/cherrytree/modules/main.py", line 247, in main
    CherryTreeHandler(args, lang_str)
  File "/usr/share/cherrytree/modules/main.py", line 83, in __init__
    self.window_open_new(args.filepath, args.node, True, True if args.filepath else False)
  File "/usr/share/cherrytree/modules/main.py", line 88, in window_open_new
    window = core.CherryTree(self.lang_str, filepath, node_name, self, is_startup, is_arg, False)
  File "/usr/share/cherrytree/modules/core.py", line 252, in __init__
    self.file_startup_load(open_with_file, node_name)
  File "/usr/share/cherrytree/modules/core.py", line 1500, in file_startup_load
    self.file_load(os.path.join(self.file_dir, self.file_name))
  File "/usr/share/cherrytree/modules/core.py", line 2002, in file_load
    self.ctdb_handler.read_db_full(self.db, discard_ids=None)
  File "/usr/share/cherrytree/modules/ctdb.py", line 644, in read_db_full
    bookmarks_rows = db.execute('SELECT * FROM bookmark ORDER BY sequence ASC').fetchall()
sqlite3.DatabaseError: database disk image is malformed
`

I had saw a similar issue which was resolved by opening the file with with same name and tilde
but in my case the tilde files got disappeared after i tried to open the original file 1-2 times.

**Comment by txe** [comment]
Well, that sounds bad, looks like the file was already corrupted (due to disk errors or during network coping) and you lost backup because of bad program logic.
I really hope you have a copy of the file somewhere.

Still, the file is just an SQlite database and there is a possibility of recovery; read, for example, [this article](https://techblog.dorogin.com/sqliteexception-database-disk-image-is-malformed-77e59d547c50). Before doing something with the file, make a copy of it.

**Comment by hellrider9** [comment]
The disk errors keep coming with me as i use dual boot linux and windows
Is there any solution to that

**Comment by txe** [comment]
the solution is described in https://techblog.dorogin.com/sqliteexception-database-disk-image-is-malformed-77e59d547c50
