### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by DengNing** [giuspen/cherrytree#74]
Traceback (most recent call last):
  File "core.pyc", line 1324, in file_open
  File "core.pyc", line 1330, in filepath_open
  File "core.pyc", line 1027, in modification_time_update_value
  File "genericpath.pyc", line 54, in getmtime
WindowsError: [Error 3] : ''
Traceback (most recent call last):
  File "core.pyc", line 1213, in file_save
  File "core.pyc", line 1304, in file_write
  File "core.pyc", line 1256, in file_write_low_level
MemoryError

my cherrytree file has been 47.6MB，it always show the error about fail to write ，and the time to save file every time is take too long

**Comment by txe** [comment]
Not enough information
